[package]
name = "hello_guys"
version = "0.1.0"
authors = ["yatender-oktalk <yatender.nitk@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
